Bump decidim from v0.28.0 to v0.28.1
decidim/metadecidim pull request #128
Opened 2024-06-19 10:37 UTC by andreslucena

As the title says, there's a new version of Decidim so we need to update

2024-06-19 10:38 UTC, andreslucena commented
To finish the update process, once this is deployed in the production database we'll need to run 

`bin/rails decidim:upgrade:fix_orphan_categorizations` 

See more information at https://github.com/decidim/decidim/releases/tag/v0.28.1

2024-06-19 12:27 UTC, alecslupu approved these changes
Lgtm.

@andreslucena  please merge when you need.

2024-06-19 14:22 UTC, fblupi requested changes

2024-06-19 14:22 UTC, fblupi commented on package.json
As we are not using the `file:packages/dir` anymore here, we could remove the `packages` directory

2024-06-19 14:28 UTC, andreslucena commented on package.json
Done at 4efbd08c2032705e2b3587a3b57e1f141480a5cb

2024-06-20 09:33 UTC, fblupi reviewed
@andreslucena I receive this error while compiling the assets.

```
(58:6) /Users/fbo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/decidim-meetings-0.28.1/app/packs/stylesheets/decidim/meetings/_item.scss The `min-w-24` class does not exist. If `min-w-24` is a custom class, make sure it is defined within a `@layer` directive.

  56 | 
  57 |     &__lg {
> 58 |       @apply w-fit justify-center [&>*]:px-2 min-w-24 h-[8.5rem];
     |      ^
  59 |     }
  60 | 
```

I tried deploying it in Heroku thinking it was something on my local, but it's failing with the same error too.

I don't get why it's not failing in the CI then.

2024-06-20 13:28 UTC, andreslucena commented
> (58:6) /Users/fbo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/decidim-meetings-0.28.1/app/packs/stylesheets/decidim/meetings/_item.scss The `min-w-24` class does not exist. If `min-w-24` is a custom class, make sure it is defined within a `@layer` directive.

I can reproduce this same error locally with 

`SECRET_KEY_BASE=potato RAILS_ENV=production bin/rails assets:precompile`

I think it's related to the tailwindcss version that we're using and the backport that introduced this change in v0.28 (#12787). This is using a directive that isn't available in the version of tailwind that we're using in v0.28.

I made a quick fix in bfb306cf7cadf6ad9b8602c16b327d404bd908e7, just to check out if this is indeed the problem, so we can also introduce that change in `release/0.28-stable` (and do a v0.28.2 with this fix). 

This is something that @microstudi mentioned a couple of weeks ago, but I could only reproduce in this app with this change. Locally with a new v0.28.1 app I could not reproduce this bug, as I see that it generates the app with tailwind 3.4.4. 

I think the actual issue is that we're using the caret character (`^`) and this applies to minor and patch version, and we should use the tilde character (`~`). With that, I understand that we would have detected the problem in CI (as we should have done).

2024-06-20 14:13 UTC, fblupi approved these changes
I have successfully executed it locally after applying the latest change.

Seems there's an error in the CI but, as it's not related with this and the tests run successfully locally, I approve it.

2024-07-12 10:55 UTC, merged