Remove leftovers from proposals' states overrides
decidim/metadecidim pull request #131
Opened 2024-07-25 14:39 UTC by andreslucena

In #121 we have added some overrides, that we removed most of them we we've done the v0.29.0.rc3 update as this feature (changing proposal states strings and colors) is native now. 

This PR removes a few leftovers from it.

2024-07-25 14:49 UTC, fblupi approved these changes

2024-07-25 15:22 UTC, fblupi requested changes
As we have two custom states. We should have the translations for them:

- `decidim.proposals.answers.accepted_in_progress`
- `decidim.proposals.answers.finished`

Edit: Not needed anymore once [this fix](https://github.com/decidim/decidim/pull/13219) is deployed.

2024-07-25 15:40 UTC, andreslucena commented
Are these custom states in the database? As far as I remember the overrides that I made were 100% for helpers/strings/cell.

2024-07-29 07:15 UTC, fblupi approved these changes

2024-07-30 08:02 UTC, fblupi commented
> > As we have two custom states. We should have the translations for them:
> 
> Just to leave it here, but I think this behavior that you've seen was related to the bug described at #13219, so I think we don't need to add these i18n strings. Maybe when we deploy the next RC can you check out if the bug is still there?

Sure!

2024-07-30 11:44 UTC, merged